openapi: 3.0.3
info:
  title: Bookmark Chat API
  version: 1.0.0
  description: API for bookmark chat application

servers:
  - url: http://localhost:8080

paths:
  /:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello World!"